In [19]:
import numpy as np

array1 = np.arange(100)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
array1 = array1.reshape(10,10)
print(array1)
#first value is the row and second is the column
print(array1[1][3])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
13


In [21]:
#reshape to 3 dimentional array
array1 = array1.reshape(5,4,5)
print(array1)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [25]:
print(array1[4])
print(array1[0][1])
print(array1[0][1][2])

[[80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
[5 6 7 8 9]
7


In [26]:
#array operations
array1 = np.arange(100)
array1 = array1.reshape(5,4,5)
print(array1)

array2 = np.arange(100)
array2 = array2.reshape(5,4,5)
print(array2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [27]:
array3 = np.add(array1,array2)
print(array3)

[[[  0   2   4   6   8]
  [ 10  12  14  16  18]
  [ 20  22  24  26  28]
  [ 30  32  34  36  38]]

 [[ 40  42  44  46  48]
  [ 50  52  54  56  58]
  [ 60  62  64  66  68]
  [ 70  72  74  76  78]]

 [[ 80  82  84  86  88]
  [ 90  92  94  96  98]
  [100 102 104 106 108]
  [110 112 114 116 118]]

 [[120 122 124 126 128]
  [130 132 134 136 138]
  [140 142 144 146 148]
  [150 152 154 156 158]]

 [[160 162 164 166 168]
  [170 172 174 176 178]
  [180 182 184 186 188]
  [190 192 194 196 198]]]


In [28]:
array3 = np.multiply(array1,array2)
print(array3)

[[[   0    1    4    9   16]
  [  25   36   49   64   81]
  [ 100  121  144  169  196]
  [ 225  256  289  324  361]]

 [[ 400  441  484  529  576]
  [ 625  676  729  784  841]
  [ 900  961 1024 1089 1156]
  [1225 1296 1369 1444 1521]]

 [[1600 1681 1764 1849 1936]
  [2025 2116 2209 2304 2401]
  [2500 2601 2704 2809 2916]
  [3025 3136 3249 3364 3481]]

 [[3600 3721 3844 3969 4096]
  [4225 4356 4489 4624 4761]
  [4900 5041 5184 5329 5476]
  [5625 5776 5929 6084 6241]]

 [[6400 6561 6724 6889 7056]
  [7225 7396 7569 7744 7921]
  [8100 8281 8464 8649 8836]
  [9025 9216 9409 9604 9801]]]


In [29]:
array3 = np.subtract(array1,array2)
print(array3)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [30]:
array3 = np.minimum(array1,array2)
print(array3)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [31]:
#transpose of array
array1 = np.arange(10).reshape(2,5)
print(array1)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [33]:
print(array1.transpose())

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### statistic operations

In [34]:
print(array1.sum())

45


In [35]:
print(array1.mean())


4.5


In [36]:
print(array1.std())

2.8722813232690143


In [37]:
print(array1.var())

8.25


### where statement for array

In [38]:
print(array1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [39]:
array2 = np.where(array1<3,0,array1)
print(array2)

[[0 0 0 3 4]
 [5 6 7 8 9]]
