In [19]:
import numpy as np

array1 = np.random.random((2,3))
print(array1)

[[0.3529456  0.87493933 0.18914341]
 [0.08876182 0.1223353  0.63770323]]


In [20]:
array2 = np.random.random((2,3))
print(array2)

[[0.92699836 0.69212459 0.90628195]
 [0.03628699 0.00913233 0.28565215]]


### Array operations 

In [26]:
array3 = array1+array2
print(array3)

[[0.48803846 1.45796339 0.91422363]
 [0.37137926 1.07135007 1.13083856]]


In [22]:
array3 = array1-array2
print(array3)

[[-0.57405275  0.18281474 -0.71713854]
 [ 0.05247483  0.11320297  0.35205108]]


In [23]:
array3 = array1*array2
print(array3)

[[0.32717999 0.60556702 0.17141726]
 [0.0032209  0.00111721 0.1821613 ]]


In [24]:
array3 = array1/array2
print(array3)

[[ 0.38074027  1.2641356   0.20870261]
 [ 2.44610589 13.39584265  2.23244682]]


In [29]:
array4 = np.arange(5)
print(array4)
array4 = array4 ** 2
print(array4)

[0 1 2 3 4]
[ 0  1  4  9 16]


## numpy array indexing 

In [30]:
array5 = np.arange(10)
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
array5[4] = 7
print(array5[4])
print(array5)

7
[0 1 2 3 7 5 6 7 8 9]


In [36]:
print(array5[2:5])

[2 3 7]


In [37]:
print(array5[:])

[0 1 2 3 7 5 6 7 8 9]


In [38]:
print(array5[:5])
print(array5[2:])

[0 1 2 3 7]
[2 3 7 5 6 7 8 9]


In [39]:
array5[:5] = 1
print(array5)

[1 1 1 1 1 5 6 7 8 9]


In [40]:
array6= array5.copy()
print(array6)

[1 1 1 1 1 5 6 7 8 9]
